#!/bin/sh


# Stop on any errors
set -e

echo "-----Creating subset UFOs..."
psfsubset -i source/glyph_data.csv --header glyph_name --filter in_neo source/masters/Akatab-Regular.ufo source/masters/AkatabNeo-Regular.ufo &
wait
psfsubset -i source/glyph_data.csv --header glyph_name --filter in_neo source/masters/Akatab-Black.ufo source/masters/AkatabNeo-Black.ufo &
wait

echo "-----Updating family name metadata in subset fonts..."
perl -i -pe 's/Akatab/AkatabNeo/g' source/masters/AkatabNeo-Regular.ufo/fontinfo.plist
perl -i -pe 's/Akatab/AkatabNeo/g' source/masters/AkatabNeo-Regular.ufo/lib.plist
perl -i -pe 's/Akatab/AkatabNeo/g' source/masters/AkatabNeo-Black.ufo/fontinfo.plist
perl -i -pe 's/Akatab/AkatabNeo/g' source/masters/AkatabNeo-Black.ufo/lib.plist

echo "-----Updating WOFF metadata..."
psfmakewoffmetadata -n AkatabNeo -i "org.sil.fonts" -f FONTLOG.txt -o source/AkatabNeo-WOFF-metadata.xml source/masters/Akatab-Regular.ufo

echo "-----Subsetting completed!"