#!/bin/sh

# To generate PDFs that are somewhat OK you will need to have the Roboto and Roboto mono font families installed on your system
# https://fonts.google.com/specimen/Roboto
# https://fonts.google.com/specimen/Roboto+Mono

echo "-----Rebuilding documentation..."

echo "     >>> HTML (documentation_tirra/)"

echo "     > index.html"
pandoc -s -f markdown-smart --template documentation_tirra/source/template.html documentation_tirra/source/index.md -o documentation_tirra/index.html --lua-filter=documentation_tirra/source/pandocfilters/filter-html.lua
echo "     > about.html"
pandoc -s -f markdown-smart --template documentation_tirra/source/template.html documentation_tirra/source/about.md -o documentation_tirra/about.html --lua-filter=documentation_tirra/source/pandocfilters/filter-html.lua
echo "     > charset.html"
pandoc -s -f markdown-smart --template documentation_tirra/source/template.html documentation_tirra/source/charset.md -o documentation_tirra/charset.html --lua-filter=documentation_tirra/source/pandocfilters/filter-html.lua
echo "     > design.html"
pandoc -s -f markdown-smart --template documentation_tirra/source/template.html documentation_tirra/source/design.md -o documentation_tirra/design.html --lua-filter=documentation_tirra/source/pandocfilters/filter-html.lua
echo "     > developer.html"
pandoc -s -f markdown-smart --template documentation_tirra/source/template.html documentation_tirra/source/developer.md -o documentation_tirra/developer.html --lua-filter=documentation_tirra/source/pandocfilters/filter-html.lua
echo "     > faq.html"
pandoc -s -f markdown-smart --template documentation_tirra/source/template.html documentation_tirra/source/faq.md -o documentation_tirra/faq.html --lua-filter=documentation_tirra/source/pandocfilters/filter-html.lua
# echo "     > features.html"
# pandoc -s -f markdown-smart --template documentation_tirra/source/template.html documentation_tirra/source/features.md -o documentation_tirra/features.html --lua-filter=documentation_tirra/source/pandocfilters/filter-html.lua
echo "     > history.html"
pandoc -s -f markdown-smart --template documentation_tirra/source/template.html documentation_tirra/source/history.md -o documentation_tirra/history.html --lua-filter=documentation_tirra/source/pandocfilters/filter-html.lua
echo "     > resources.html"
pandoc -s -f markdown-smart --template documentation_tirra/source/template.html documentation_tirra/source/resources.md -o documentation_tirra/resources.html --lua-filter=documentation_tirra/source/pandocfilters/filter-html.lua
echo "     > support.html"
pandoc -s -f markdown-smart --template documentation_tirra/source/template.html documentation_tirra/source/support.md -o documentation_tirra/support.html --lua-filter=documentation_tirra/source/pandocfilters/filter-html.lua
echo "     > versions.html"
pandoc -s -f markdown-smart --template documentation_tirra/source/template.html documentation_tirra/source/versions.md -o documentation_tirra/versions.html --lua-filter=documentation_tirra/source/pandocfilters/filter-html.lua
# echo "     > markdowntest.html"
# pandoc -s -f markdown-smart --template documentation_tirra/source/template.html documentation_tirra/source/markdowntest.md -o documentation_tirra/markdowntest.html --lua-filter=documentation_tirra/source/pandocfilters/filter-html.lua

echo "     >>> PDF (documentation_tirra/pdf/)"
mkdir -p documentation_tirra/source/pdftemp

echo "     > index.html > index.pdf"
pandoc -s -f markdown-smart --template documentation_tirra/source/templatepdf.html documentation_tirra/source/index.md -o documentation_tirra/source/pdftemp/index.html --lua-filter=documentation_tirra/source/pandocfilters/filter-pdf.lua
weasyprint documentation_tirra/source/pdftemp/index.html documentation_tirra/pdf/index.pdf
echo "     > about.html > about.pdf"
pandoc -s -f markdown-smart --template documentation_tirra/source/templatepdf.html documentation_tirra/source/about.md -o documentation_tirra/source/pdftemp/about.html --lua-filter=documentation_tirra/source/pandocfilters/filter-pdf.lua
weasyprint documentation_tirra/source/pdftemp/about.html documentation_tirra/pdf/about.pdf
echo "     > charset.html > charset.pdf"
pandoc -s -f markdown-smart --template documentation_tirra/source/templatepdf.html documentation_tirra/source/charset.md -o documentation_tirra/source/pdftemp/charset.html --lua-filter=documentation_tirra/source/pandocfilters/filter-pdf.lua
weasyprint documentation_tirra/source/pdftemp/charset.html documentation_tirra/pdf/charset.pdf
echo "     > design.html > design.pdf"
pandoc -s -f markdown-smart --template documentation_tirra/source/templatepdf.html documentation_tirra/source/design.md -o documentation_tirra/source/pdftemp/design.html --lua-filter=documentation_tirra/source/pandocfilters/filter-pdf.lua
weasyprint documentation_tirra/source/pdftemp/design.html documentation_tirra/pdf/design.pdf
echo "     > developer.html > developer.pdf"
pandoc -s -f markdown-smart --template documentation_tirra/source/templatepdf.html documentation_tirra/source/developer.md -o documentation_tirra/source/pdftemp/developer.html --lua-filter=documentation_tirra/source/pandocfilters/filter-pdf.lua
weasyprint documentation_tirra/source/pdftemp/developer.html documentation_tirra/pdf/developer.pdf
echo "     > faq.html > faq.pdf"
pandoc -s -f markdown-smart --template documentation_tirra/source/templatepdf.html documentation_tirra/source/faq.md -o documentation_tirra/source/pdftemp/faq.html --lua-filter=documentation_tirra/source/pandocfilters/filter-pdf.lua
weasyprint documentation_tirra/source/pdftemp/faq.html documentation_tirra/pdf/faq.pdf
# echo "     > features.html > features.pdf"
# pandoc -s -f markdown-smart --template documentation_tirra/source/templatepdf.html documentation_tirra/source/features.md -o documentation_tirra/source/pdftemp/features.html --lua-filter=documentation_tirra/source/pandocfilters/filter-pdf.lua
# weasyprint documentation_tirra/source/pdftemp/features.html documentation_tirra/pdf/features.pdf
echo "     > history.html > history.pdf"
pandoc -s -f markdown-smart --template documentation_tirra/source/templatepdf.html documentation_tirra/source/history.md -o documentation_tirra/source/pdftemp/history.html --lua-filter=documentation_tirra/source/pandocfilters/filter-pdf.lua
weasyprint documentation_tirra/source/pdftemp/history.html documentation_tirra/pdf/history.pdf
echo "     > resources.html > resources.pdf"
pandoc -s -f markdown-smart --template documentation_tirra/source/templatepdf.html documentation_tirra/source/resources.md -o documentation_tirra/source/pdftemp/resources.html --lua-filter=documentation_tirra/source/pandocfilters/filter-pdf.lua
weasyprint documentation_tirra/source/pdftemp/resources.html documentation_tirra/pdf/resources.pdf
echo "     > support.html > support.pdf"
pandoc -s -f markdown-smart --template documentation_tirra/source/templatepdf.html documentation_tirra/source/support.md -o documentation_tirra/source/pdftemp/support.html --lua-filter=documentation_tirra/source/pandocfilters/filter-pdf.lua
weasyprint documentation_tirra/source/pdftemp/support.html documentation_tirra/pdf/support.pdf
echo "     > versions.html > versions.pdf"
pandoc -s -f markdown-smart --template documentation_tirra/source/templatepdf.html documentation_tirra/source/versions.md -o documentation_tirra/source/pdftemp/versions.html --lua-filter=documentation_tirra/source/pandocfilters/filter-pdf.lua
weasyprint documentation_tirra/source/pdftemp/versions.html documentation_tirra/pdf/versions.pdf
# echo "     > markdowntest.html > markdowntest.pdf"
# pandoc -s -f markdown-smart --template documentation_tirra/source/templatepdf.html documentation_tirra/source/markdowntest.md -o documentation_tirra/source/pdftemp/markdowntest.html --lua-filter=documentation_tirra/source/pandocfilters/filter-pdf.lua
# weasyprint documentation_tirra/source/pdftemp/markdowntest.html documentation_tirra/pdf/markdowntest.pdf

echo "     >>> PRODUCT SITE MARKDOWN (documentation_tirra/source/productsite/)"

echo "     > about.md"
python3 documentation_tirra/source/makepsmd.py documentation_tirra/source/about.md documentation_tirra/source/productsite/about.md -q
echo "     > charset.md"
python3 documentation_tirra/source/makepsmd.py documentation_tirra/source/charset.md documentation_tirra/source/productsite/charset.md -q
echo "     > design.md"
python3 documentation_tirra/source/makepsmd.py documentation_tirra/source/design.md documentation_tirra/source/productsite/design.md -q
echo "     > developer.md"
python3 documentation_tirra/source/makepsmd.py documentation_tirra/source/developer.md documentation_tirra/source/productsite/developer.md -q
echo "     > faq.md"
python3 documentation_tirra/source/makepsmd.py documentation_tirra/source/faq.md documentation_tirra/source/productsite/faq.md -q
# echo "     > features.md"
# python3 documentation_tirra/source/makepsmd.py documentation_tirra/source/features.md documentation_tirra/source/productsite/features.md -q
echo "     > history.md"
python3 documentation_tirra/source/makepsmd.py documentation_tirra/source/history.md documentation_tirra/source/productsite/history.md -q
echo "     > resources.md"
python3 documentation_tirra/source/makepsmd.py documentation_tirra/source/resources.md documentation_tirra/source/productsite/resources.md -q
echo "     > support.md"
python3 documentation_tirra/source/makepsmd.py documentation_tirra/source/support.md documentation_tirra/source/productsite/support.md -q
# echo "     > markdowntest.md"
# python3 documentation_tirra/source/makepsmd.py documentation_tirra/source/markdowntest.md documentation_tirra/source/productsite/markdowntest.md -q
echo "     Markdown source for other Product Site pages is in separate repo"

echo "-----Completed!"
