#!/bin/sh


# Stop on any errors
set -e

echo "-----Update version number..."
#psfsetversion source/masters/Akatab-Regular.ufo "0.937" -l source/logs/setversionR.log

echo "-----Updating production names in Regular..."
psfsetpsnames -q -i source/glyph_data.csv source/masters/Akatab-Regular.ufo -p backup=False

echo "-----Updating glyph orders in Regular..."
psfsetglyphorder -q --header sort_final -i source/glyph_data.csv source/masters/Akatab-Regular.ufo -p backup=False

echo "-----Normalising UFO..."
psfnormalize -p checkfix=fix source/masters/Akatab-Regular.ufo -l source/masters/logs/normR.log

echo "-----Updating woff metadata file..."
psfmakewoffmetadata -n Akatab -i org.sil.fonts -o source/Akatab-WOFF-metadata.xml source/masters/Akatab-Regular.ufo -l source/masters/logs/makewoff.log

echo "-----Preflight completed!"