#!/bin/sh


# Stop on any errors
set -e

echo "-----Update version number..."
# psfsetversion source/masters/Akatab-Regular.ufo "2.002" -l source/logs/setversionR.log

echo "-----Check and normalize Regular & Black..."
psfnormalize -p checkfix=fix source/masters/Akatab-Regular.ufo -l source/masters/logs/normReg.log &
psfnormalize -p checkfix=fix source/masters/Akatab-Black.ufo -l source/masters/logs/normBlack.log &
wait

echo "-----Updating glyph orders in Regular..."
psfsetglyphorder -q --header sort_final -i source/glyph_data.csv source/masters/Akatab-Regular.ufo -p backup=False

echo "-----Updating production names in Regular..."
psfsetpsnames -q -i source/glyph_data.csv source/masters/Akatab-Regular.ufo -p backup=False

echo "-----Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters source/*.designspace -l source/logs/sync.log

echo "-----Updating woff metadata file..."
psfmakewoffmetadata -n Akatab -i org.sil.fonts -o source/Akatab-WOFF-metadata.xml source/masters/Akatab-Regular.ufo -l source/masters/logs/makewoff.log

echo "-----Preflight completed!"