#!/bin/sh
# script to convert UFOs to glyphs file for editing
DESIGNSPACE=source/akatab.designspace
OUTPUT=source/masters/Akatab.glyphs

echo "Converting UFO(s) in '$DESIGNSPACE' to '$OUTPUT'"
psfufo2glyphs $DESIGNSPACE $OUTPUT