#!/bin/sh


# Stop on any errors
set -e

echo "-----Creating subset UFOs..."
psfsubset -i glyph_data.csv --header glyph_name --filter in_neo masters/Akatab-Regular.ufo subset-neo/source/masters/AkatabNeo-Regular.ufo &
wait
psfsubset -i glyph_data.csv --header glyph_name --filter in_neo masters/Akatab-Black.ufo subset-neo/source/masters/AkatabNeo-Black.ufo &
wait

echo "-----Updating family name metadata in subset fonts..."
perl -i -pe 's/Akatab/AkatabNeo/g' subset-neo/source/masters/AkatabNeo-Regular.ufo/fontinfo.plist
perl -i -pe 's/Akatab/AkatabNeo/g' subset-neo/source/masters/AkatabNeo-Regular.ufo/lib.plist
perl -i -pe 's/Akatab/AkatabNeo/g' subset-neo/source/masters/AkatabNeo-Black.ufo/fontinfo.plist
perl -i -pe 's/Akatab/AkatabNeo/g' subset-neo/source/masters/AkatabNeo-Black.ufo/lib.plist

echo "-----Updating WOFF metadata..."
psfmakewoffmetadata -n AkatabNeo -i "org.sil.fonts" -f subset-neo/FONTLOG.txt -o subset-neo/source/AkatabNeo-WOFF-metadata.xml masters/Akatab-Regular.ufo

echo "-----Subsetting completed!"